# Project: Project4
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = aceptavariables3.o aceptavariables4.o $(RES)
LINKOBJ  = aceptavariables3.o aceptavariables4.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = tareadevariablespareimpar3.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before tareadevariablespareimpar3.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "tareadevariablespareimpar3.exe" $(LIBS)

aceptavariables3.o: aceptavariables3.c
	$(CC) -c aceptavariables3.c -o aceptavariables3.o $(CFLAGS)

aceptavariables4.o: aceptavariables4.c
	$(CC) -c aceptavariables4.c -o aceptavariables4.o $(CFLAGS)
